module thumbdrive_multiboot.grub;

import std.algorithm : endsWith, filter, map, sort;
import std.array : array, appender;
import std.file : dirEntries, exists, mkdirRecurse, readText, SpanMode, write;
import std.format : format;
import std.path : baseName, buildPath, extension, stripExtension;
import std.string : replace, toLower, strip;

import thumbdrive_multiboot.mode;
import thumbdrive_multiboot.procutil;
import thumbdrive_multiboot.versioning;

struct InstalledOsEntry
{
    string subvol; /// e.g. @arch
    string title;
    string kernelRel; /// path under subvol, e.g. boot/vmlinuz-linux
    string initrdRel; /// may be multiple space-separated
}

struct IsoEntry
{
    string relativePath; /// e.g. isos/ubuntu.iso
    string title;
}

struct GrubMenuModel
{
    string btrfsUuid; /// empty if no pool
    string exfatUuid; /// optional
    DriveMode mode;
    InstalledOsEntry[] installs;
    IsoEntry[] isos;
}

string generateGrubCfg(const GrubMenuModel model)
{
    auto app = appender!string();
    app.put("# Generated by " ~ appName ~ " " ~ appVersion ~ "\n");
    app.put("set timeout=15\n");
    app.put("set default=0\n\n");
    app.put("insmod part_gpt\n");
    app.put("insmod fat\n");
    app.put("insmod exfat\n");
    app.put("insmod iso9660\n");
    app.put("insmod loopback\n");
    app.put("insmod btrfs\n");
    app.put("insmod all_video\n");
    app.put("insmod gfxterm\n");
    app.put("terminal_output gfxterm\n\n");

    app.put(format("menuentry \"%s — About\" {\n", appName));
    app.put("    echo \"" ~ appName ~ " " ~ appVersion ~ "\"\n");
    app.put("    echo \"Mode: " ~ modeId(model.mode) ~ "\"\n");
    app.put("    sleep 5\n");
    app.put("}\n\n");

    foreach (os; model.installs)
    {
        auto title = os.title.length ? os.title : os.subvol;
        app.put(format("menuentry \"%s\" {\n", title.replace(`"`, `\"`)));
        if (model.btrfsUuid.length)
        {
            app.put(format("    search --no-floppy --fs-uuid --set=root %s\n", model.btrfsUuid));
        }
        else
        {
            app.put("    search --file --set=root /" ~ os.subvol ~ "/" ~ os.kernelRel ~ "\n");
        }
        auto rootflags = "subvol=" ~ os.subvol ~ ",compress=zstd:2";
        app.put(format("    linux /%s/%s root=UUID=%s rootflags=%s rw\n",
                os.subvol, os.kernelRel,
                model.btrfsUuid.length ? model.btrfsUuid : "UNKNOWN",
                rootflags));
        auto initrds = os.initrdRel.length ? os.initrdRel : "boot/initramfs-linux.img";
        // Support multiple initrd paths separated by spaces
        import std.string : split;

        auto parts = initrds.split();
        string initrdLine = "    initrd";
        foreach (p; parts)
            initrdLine ~= format(" /%s/%s", os.subvol, p);
        app.put(initrdLine ~ "\n");
        app.put("}\n\n");
    }

    foreach (iso; model.isos)
    {
        auto title = iso.title.length ? iso.title : baseName(iso.relativePath);
        auto isofile = "/" ~ iso.relativePath.replace(`\`, `/`);
        app.put(format("menuentry \"%s\" {\n", title.replace(`"`, `\"`)));
        app.put(format("    set isofile=\"%s\"\n", isofile));
        // Prefer exFAT/ESP search by filename
        app.put("    search --file --set=root $isofile\n");
        app.put("    loopback loop $isofile\n");
        app.put("    # Prefer distro loopback.cfg when present\n");
        app.put("    if [ -f (loop)/boot/grub/loopback.cfg ]; then\n");
        app.put("        root=(loop)\n");
        app.put("        configfile /boot/grub/loopback.cfg\n");
        app.put("    elif [ -f (loop)/casper/vmlinuz ]; then\n");
        app.put("        linux (loop)/casper/vmlinuz boot=casper iso-scan/filename=$isofile quiet splash\n");
        app.put("        initrd (loop)/casper/initrd\n");
        app.put("    elif [ -f (loop)/casper/vmlinuz.efi ]; then\n");
        app.put("        linux (loop)/casper/vmlinuz.efi boot=casper iso-scan/filename=$isofile quiet splash\n");
        app.put("        initrd (loop)/casper/initrd\n");
        app.put("    elif [ -f (loop)/arch/boot/x86_64/vmlinuz-linux ]; then\n");
        app.put("        linux (loop)/arch/boot/x86_64/vmlinuz-linux img_loop=$isofile\n");
        app.put("        initrd (loop)/arch/boot/intel_ucode.img (loop)/arch/boot/amd_ucode.img (loop)/arch/boot/x86_64/initramfs-linux.img\n");
        app.put("    elif [ -f (loop)/images/pxeboot/vmlinuz ]; then\n");
        app.put("        linux (loop)/images/pxeboot/vmlinuz inst.stage2=hd:LABEL=Fedora iso-scan/filename=$isofile\n");
        app.put("        initrd (loop)/images/pxeboot/initrd.img\n");
        app.put("    else\n");
        app.put("        echo \"No known boot files inside ISO\"\n");
        app.put("        sleep 5\n");
        app.put("    fi\n");
        app.put("}\n\n");
    }

    return app.data;
}

IsoEntry[] scanIsos(string exfatRoot)
{
    IsoEntry[] out_;
    auto isoDir = buildPath(exfatRoot, "isos");
    if (!exists(isoDir))
        return out_;
    foreach (e; dirEntries(isoDir, SpanMode.shallow))
    {
        if (!e.isFile)
            continue;
        auto ext = extension(e.name).toLower();
        if (ext != ".iso" && ext != ".img")
            continue;
        IsoEntry iso;
        iso.relativePath = "isos/" ~ baseName(e.name);
        iso.title = stripExtension(baseName(e.name));
        out_ ~= iso;
    }
    out_.sort!((a, b) => a.title < b.title);
    return out_;
}

InstalledOsEntry[] scanInstalls(string btrfsMount)
{
    InstalledOsEntry[] out_;
    if (!exists(btrfsMount))
        return out_;
    foreach (e; dirEntries(btrfsMount, SpanMode.shallow))
    {
        if (!e.isDir)
            continue;
        auto name = baseName(e.name);
        if (!name.length || name[0] != '@')
            continue;
        if (name == "@shared_home" || name.endsWith("_backup"))
            continue;
        // Probe common kernel paths
        string kernel;
        string initrd;
        auto candidates = [
            ["boot/vmlinuz-linux", "boot/initramfs-linux.img"],
            ["boot/vmlinuz", "boot/initrd.img"],
            ["vmlinuz", "initrd.img"],
        ];
        foreach (c; candidates)
        {
            if (exists(buildPath(e.name, c[0])))
            {
                kernel = c[0];
                initrd = exists(buildPath(e.name, c[1])) ? c[1] : "";
                break;
            }
        }
        // Debian/Ubuntu versioned vmlinuz
        if (!kernel.length)
        {
            auto boot = buildPath(e.name, "boot");
            if (exists(boot))
            {
                foreach (f; dirEntries(boot, SpanMode.shallow))
                {
                    auto bn = baseName(f.name);
                    if (bn.length > 8 && bn[0 .. 8] == "vmlinuz-")
                    {
                        kernel = "boot/" ~ bn;
                        auto ver = bn[8 .. $];
                        auto initName = "boot/initrd.img-" ~ ver;
                        if (exists(buildPath(e.name, initName)))
                            initrd = initName;
                        break;
                    }
                }
            }
        }
        if (!kernel.length)
            continue;
        InstalledOsEntry os;
        os.subvol = name;
        os.title = name[1 .. $]; // strip @
        os.kernelRel = kernel;
        os.initrdRel = initrd;
        out_ ~= os;
    }
    out_.sort!((a, b) => a.title < b.title);
    return out_;
}

/// Write grub.cfg under ESP mount (EFI/debian or boot/grub).
void writeGrubCfgToEsp(string espMount, string cfg)
{
    auto paths = [
        buildPath(espMount, "boot", "grub", "grub.cfg"),
        buildPath(espMount, "EFI", "thumbdrive-multiboot", "grub.cfg"),
        buildPath(espMount, "EFI", "BOOT", "grub.cfg"),
    ];
    foreach (p; paths)
    {
        mkdirRecurse(p[0 .. $ - baseName(p).length]);
        write(p, cfg);
    }
}

/// Install GRUB EFI when grub-install is available; otherwise copy note for bundled EFI.
struct GrubInstallResult
{
    bool installed;
    string message;
}

GrubInstallResult installGrubEfi(string espMount, string diskDevice = null)
{
    if (!commandExists("grub-install") && !commandExists("grub2-install"))
    {
        // Ensure removable path exists for a future bundled BOOTX64.EFI
        mkdirRecurse(buildPath(espMount, "EFI", "BOOT"));
        mkdirRecurse(buildPath(espMount, "boot", "grub"));
        write(buildPath(espMount, "EFI", "BOOT", "README-TMB.txt"),
                "Place BOOTX64.EFI here or run grub-install from a Linux host.\n"
                    ~ "Thumbdrive Multiboot writes grub.cfg beside this file.\n");
        return GrubInstallResult(false,
                "grub-install not found; wrote ESP layout and grub.cfg. "
                    ~ "Install GRUB EFI on a Linux host or ship BOOTX64.EFI into EFI/BOOT.");
    }

    auto bin = commandExists("grub-install") ? "grub-install" : "grub2-install";
    string[] args = [
        bin,
        "--target=x86_64-efi",
        "--efi-directory=" ~ espMount,
        "--boot-directory=" ~ buildPath(espMount, "boot"),
        "--removable",
        "--recheck",
    ];
    if (diskDevice.length)
        args ~= diskDevice;
    auto r = runArgv(args);
    if (r.status != 0)
        return GrubInstallResult(false, "grub-install failed: " ~ r.output);
    return GrubInstallResult(true, "GRUB EFI installed to " ~ espMount);
}

string readUuidIfExists(string path)
{
    // Linux: blkid -s UUID -o value PATH
    if (!commandExists("blkid"))
        return "";
    auto r = runArgv(["blkid", "-s", "UUID", "-o", "value", path]);
    if (r.status != 0)
        return "";
    return r.output.strip;
}
